# Generated by Django 3.0.7 on 2020-09-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='title',
            new_name='cartitle',
        ),
    ]
